import { Item, User, ClaimRequest, ActivityLog } from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_john',
    name: 'John Doe',
    email: 'j.doe@university.edu',
    avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBALmeD0jHHqe-FvAIiC58dL06wTpxK6YRImjPnZRNj6IjKH-qBiQFPU7S0ceXP7m0AjjXdXrgikGKYwOdejbRzSpx05rOH2DKkkLgVAGbNbhRgwd_OOQveKikEIX21jAQp9v24GxI7-Xe-Irvk84T4O_1aSKG7fFeN35oQmsUEoNXLFhAqKKyrwlDWPOF7yj46gnBM4kGb6mTAGmgoo-3K0b9oJPzasjFRuVUoK-vpJ4d6US7X42c3Zc6i0g6XqCxtZwInOnhwKT0',
    role: 'student',
    department: 'Computer Science',
    karmaPoints: 120,
    itemsReportedCount: 3,
    itemsResolvedCount: 2,
    responseRate: '98%',
    isVerified: true,
  },
  {
    id: 'usr_sarah',
    name: 'Sarah Jenkins',
    email: 's.jenkins@university.edu',
    avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDVBaqHvRkKTRymhte9qeP9sw12DxY4_azlQC9PWYfScmojcFoXe90MLA0zyOhkIJLEwdWF7rQISMC0U00Jtgmar6ndNxQPZA-EKXZE8rJ8WtnThF8tSZTIKaeuThUuygBOI2Aeg0dOCmP2wD9n0eioS93T_vpAlPqqBV98p59_MBFTreKu_ZzL3k5iZ3Gz-LegskFgR4AuzvWEGQigSC16fAWHvQlEh8eHFbpLwIZX8MIg_0liz33_OOq8YzEs729TEuAzRwgVTeM',
    role: 'student',
    department: 'Bioengineering',
    karmaPoints: 240,
    itemsReportedCount: 7,
    itemsResolvedCount: 5,
    responseRate: '100%',
    isVerified: true,
  },
  {
    id: 'usr_admin',
    name: 'Dr. Robert Vance (Campus Admin)',
    email: 'admin.lostfound@university.edu',
    avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDpexsvgPi6GB15nHlLoZCeZ0cYhHBLdfrYinpePSCjDqH-Na11weSEQ-U7N_YpeuAqRO84XmqEBWgfBT2KgEGP73NMr7p1mjBVXHDOBQmo5TlJlFYV_vzVH8KZtcL5k2YStUaF0s9xeb-hyKnLgbakeTzY09PT1hxpVFoUq7Y1leTklxQw8Fa5nxz4M8oBl1eBN6JL7T0DkkRPpyIgRd2_jl_zO-0OppsXjer3C-9Oi_71P_MvNL0TZ1sDp0dAHKs6yihQoAlSBt0',
    role: 'admin',
    department: 'Campus Safety & Services',
    karmaPoints: 950,
    itemsReportedCount: 42,
    itemsResolvedCount: 38,
    responseRate: '100%',
    isVerified: true,
  }
];

export const INITIAL_ITEMS: Item[] = [
  {
    id: 'itm_001',
    title: 'Silver MacBook Pro 14" (2023)',
    category: 'Electronics',
    type: 'found',
    status: 'active',
    description: 'Found on 2nd Floor Science Library, desk near quiet study section. Has a subtle dark green protective shell and a sticker with a constellation.',
    primaryColor: 'Silver',
    brand: 'Apple',
    location: {
      building: 'Science & Engineering Library',
      roomOrArea: '2nd Floor Quiet Zone',
      campusZone: 'Library Complex',
      lat: 37.8719,
      lng: -122.2585,
    },
    dateReported: '2025-05-12',
    timeReported: '14:30',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBV6AjX73OcB5FH56zIsJ_0oSQ_j0a19Ffh3f6ucUWrA6H1Bhq4R6m8xItB4RTLCO6wD4SwmDK6aRkWPkHZJEG1_FflE5ObbKOKxYo1ztlMcjfx08kH51T6bu4A_FOG90Aq-7vf1YDf3AjKaotMECoWva92nc44BXECmvDCzItYW7VOqsFBStFvCalVVPe6byeOkQ4k_GmR31lbHZjH3ByIbZPr4yQ-4D0pxMBMW73N3hXuYQFnBwdmUN09sVqmwFJmxfF3bWV0myA',
    reportedBy: {
      id: 'usr_sarah',
      name: 'Sarah Jenkins',
      avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDVBaqHvRkKTRymhte9qeP9sw12DxY4_azlQC9PWYfScmojcFoXe90MLA0zyOhkIJLEwdWF7rQISMC0U00Jtgmar6ndNxQPZA-EKXZE8rJ8WtnThF8tSZTIKaeuThUuygBOI2Aeg0dOCmP2wD9n0eioS93T_vpAlPqqBV98p59_MBFTreKu_ZzL3k5iZ3Gz-LegskFgR4AuzvWEGQigSC16fAWHvQlEh8eHFbpLwIZX8MIg_0liz33_OOq8YzEs729TEuAzRwgVTeM',
      email: 's.jenkins@university.edu',
      role: 'student',
    },
    contactPreference: 'in_app',
    storageLocation: 'Library Information Desk (Checked In)',
    tags: ['MacBook', 'Laptop', 'Apple', 'Library'],
    createdAt: '2025-05-12T14:30:00Z',
    updatedAt: '2025-05-12T14:30:00Z',
  },
  {
    id: 'itm_002',
    title: 'Blue Lanyard with Dorm Keys & USB',
    category: 'Keys & Cards',
    type: 'found',
    status: 'active',
    description: 'Found near Central Quad fountain bench. Includes 3 keys, a brass fob, and a 64GB Kingston USB flash drive with a red cap.',
    primaryColor: 'Blue',
    brand: 'University Housing',
    location: {
      building: 'Central Quad',
      roomOrArea: 'North Fountain Benches',
      campusZone: 'Central Quad',
      lat: 37.8715,
      lng: -122.2590,
    },
    dateReported: '2025-05-11',
    timeReported: '10:15',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCQxEAz6H9uNRGyE9H1mBXRIBrUD93NoVfItLxByLidab8PYu4B4nTvXUuYbeWu-zAQFbbxWLvqW1IRBJweP57k5QblaUJh7YePKiv_izekErwgu85x82qXP2pt5rhERV3KO_EAWwC0KC2-JkqL412UVA64TlLdaElJHxm3q53YBR1fPWKfDgzg8YvROQFA5BXqpSHoLVptXA_k2nqFXhwKP90J-f8uOwXLpXOI0-V_edEQ5lr9iIkMFjFEXIBecpvsPjve5O0_AP4',
    reportedBy: {
      id: 'usr_john',
      name: 'John Doe',
      avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBALmeD0jHHqe-FvAIiC58dL06wTpxK6YRImjPnZRNj6IjKH-qBiQFPU7S0ceXP7m0AjjXdXrgikGKYwOdejbRzSpx05rOH2DKkkLgVAGbNbhRgwd_OOQveKikEIX21jAQp9v24GxI7-Xe-Irvk84T4O_1aSKG7fFeN35oQmsUEoNXLFhAqKKyrwlDWPOF7yj46gnBM4kGb6mTAGmgoo-3K0b9oJPzasjFRuVUoK-vpJ4d6US7X42c3Zc6i0g6XqCxtZwInOnhwKT0',
      email: 'j.doe@university.edu',
      role: 'student',
    },
    contactPreference: 'email',
    storageLocation: 'Student Union Help Desk',
    tags: ['Keys', 'Lanyard', 'Dorm', 'Quad'],
    createdAt: '2025-05-11T10:15:00Z',
    updatedAt: '2025-05-11T10:15:00Z',
  },
  {
    id: 'itm_003',
    title: 'Black Frame Prescription Eyeglasses',
    category: 'Eyewear',
    type: 'lost',
    status: 'active',
    description: 'Lost my Warby Parker matte black acetate frame glasses. Might have slipped out of my pouch during CS 101 lecture in Wheeler Hall.',
    primaryColor: 'Black',
    brand: 'Warby Parker',
    location: {
      building: 'Wheeler Hall Auditorium',
      roomOrArea: 'Row G Seat 12',
      campusZone: 'Central Quad',
      lat: 37.8710,
      lng: -122.2580,
    },
    dateReported: '2025-05-10',
    timeReported: '16:45',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCBSr1x7a9GaSK5j-YGXPJEKsHKEOjix9DiDlDBY6e8HN3eRayNL0ygDNSo0A_N069_vq5DJ8Ocn4VPgAuVpsuchixN4030h24nMQI5ABX-x0QKJeYcmvCOD1JTm9cNWNSvUri4BrHF8FP40Eiz8Pubr6eMi9M9Q47J2NJj2f2b26jM3UQk4T4nZ_V9q7ndE6heZK2l64Lcz2izD4pHceLWP43QS7soZ2LpumpdNPB_JcjRXgeHxqckVuaHNUPuEgWPULql_3sEdSc',
    reportedBy: {
      id: 'usr_john',
      name: 'John Doe',
      avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBALmeD0jHHqe-FvAIiC58dL06wTpxK6YRImjPnZRNj6IjKH-qBiQFPU7S0ceXP7m0AjjXdXrgikGKYwOdejbRzSpx05rOH2DKkkLgVAGbNbhRgwd_OOQveKikEIX21jAQp9v24GxI7-Xe-Irvk84T4O_1aSKG7fFeN35oQmsUEoNXLFhAqKKyrwlDWPOF7yj46gnBM4kGb6mTAGmgoo-3K0b9oJPzasjFRuVUoK-vpJ4d6US7X42c3Zc6i0g6XqCxtZwInOnhwKT0',
      email: 'j.doe@university.edu',
      role: 'student',
    },
    contactPreference: 'in_app',
    tags: ['Glasses', 'Eyewear', 'Wheeler', 'Prescription'],
    createdAt: '2025-05-10T16:45:00Z',
    updatedAt: '2025-05-10T16:45:00Z',
  },
  {
    id: 'itm_004',
    title: 'Navy Blue Hydro Flask 32oz',
    category: 'Bottles & Containers',
    type: 'found',
    status: 'active',
    description: 'Navy blue stainless steel water bottle with straw lid. Features stickers from National Parks and a California Republic flag.',
    primaryColor: 'Navy Blue',
    brand: 'Hydro Flask',
    location: {
      building: 'Recreation & Student Health Center',
      roomOrArea: 'Basketball Court 2 Bleachers',
      campusZone: 'Athletic Center',
      lat: 37.8690,
      lng: -122.2610,
    },
    dateReported: '2025-05-09',
    timeReported: '18:20',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDAdd6DDoBVMxXVvgGgp9DQoaE2MquEBBCqkIAMh3fB70VC-J7UtBcyqVxMdwlylWyw2-xivxwApxhnXFLxqll_aGGGDrm9AdL6E4eNbKr6Q9UtGPCYDWVu5ec4Mt_drPZjzxvf8FunwVTm35kdpIu48PBqotKwlrylMCQh3aDsoOpz5_ydSezIUxBSDKo8wCoFMbmIQiAUvGaHLHXMgyvwGWSqcRYdL94UTqL8vkaPf0RIQpM7Yjbs4GSWIPeh8Elg43qXg1IfhnM',
    reportedBy: {
      id: 'usr_admin',
      name: 'Dr. Robert Vance',
      avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDpexsvgPi6GB15nHlLoZCeZ0cYhHBLdfrYinpePSCjDqH-Na11weSEQ-U7N_YpeuAqRO84XmqEBWgfBT2KgEGP73NMr7p1mjBVXHDOBQmo5TlJlFYV_vzVH8KZtcL5k2YStUaF0s9xeb-hyKnLgbakeTzY09PT1hxpVFoUq7Y1leTklxQw8Fa5nxz4M8oBl1eBN6JL7T0DkkRPpyIgRd2_jl_zO-0OppsXjer3C-9Oi_71P_MvNL0TZ1sDp0dAHKs6yihQoAlSBt0',
      email: 'admin.lostfound@university.edu',
      role: 'admin',
    },
    contactPreference: 'in_app',
    storageLocation: 'Rec Center Front Office',
    tags: ['Water Bottle', 'Hydro Flask', 'Gym'],
    createdAt: '2025-05-09T18:20:00Z',
    updatedAt: '2025-05-09T18:20:00Z',
  },
  {
    id: 'itm_005',
    title: 'AirPods Pro Gen 2 with Silicone Case',
    category: 'Audio',
    type: 'found',
    status: 'claim_pending',
    description: 'Found white AirPods charging case in a translucent mint green silicone protective cover near Student Union coffee shop booth.',
    primaryColor: 'White/Mint',
    brand: 'Apple',
    location: {
      building: 'MLK Jr. Student Union',
      roomOrArea: '1st Floor Bear Cafe',
      campusZone: 'Student Union',
      lat: 37.8698,
      lng: -122.2595,
    },
    dateReported: '2025-05-08',
    timeReported: '11:00',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDG2CVIw4ECB-uni_gDHCF6a2FFqpd-euJhqm1vqeO4iYrnewwgnGS-n2kaND1UhFpUeG6lXVOZM_Eg8XJHy9EcgGdTm1pHa6IghX6fhVB-2otcZOzvUNkBT8ly42GlLXUQLPif5nuFhPal1PpwWZv9GoiUID9nhxTFsnLDNcFgEVC7ZbeVIwie83GU6CG5WCXeb_BGNNK5hidGD-m8qgWGGo3FFXlcaX_SFSnf6mLrR5wxX8Gclfmh41Z2s6AKrqaHmfCsSr-DO0o',
    reportedBy: {
      id: 'usr_sarah',
      name: 'Sarah Jenkins',
      avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDVBaqHvRkKTRymhte9qeP9sw12DxY4_azlQC9PWYfScmojcFoXe90MLA0zyOhkIJLEwdWF7rQISMC0U00Jtgmar6ndNxQPZA-EKXZE8rJ8WtnThF8tSZTIKaeuThUuygBOI2Aeg0dOCmP2wD9n0eioS93T_vpAlPqqBV98p59_MBFTreKu_ZzL3k5iZ3Gz-LegskFgR4AuzvWEGQigSC16fAWHvQlEh8eHFbpLwIZX8MIg_0liz33_OOq8YzEs729TEuAzRwgVTeM',
      email: 's.jenkins@university.edu',
      role: 'student',
    },
    contactPreference: 'in_app',
    storageLocation: 'Student Union Lockbox #12',
    tags: ['AirPods', 'Apple', 'Earbuds', 'Cafe'],
    createdAt: '2025-05-08T11:00:00Z',
    updatedAt: '2025-05-08T11:00:00Z',
  },
  {
    id: 'itm_006',
    title: 'Bose QuietComfort 45 Headphones',
    category: 'Audio',
    type: 'lost',
    status: 'active',
    description: 'Black noise cancelling over-ear Bose QC45 headphones in original zipper hard case. Left behind in Cory Hall Lab 140.',
    primaryColor: 'Black',
    brand: 'Bose',
    location: {
      building: 'Cory Hall Engineering',
      roomOrArea: 'Computer Lab 140',
      campusZone: 'Science & Engineering',
      lat: 37.8750,
      lng: -122.2570,
    },
    dateReported: '2025-05-07',
    timeReported: '20:10',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAX9nbMfWCaUNqtXihZcqoAGmVqfkDwehFtTBPwmzGotNmdrLFFkB827hNBTv3aO6l30B3ejCf5s47eGbQ2zVY9U9mBqXizTLGE6XsGGQ5VvV9Y7DN6nwhsUtDIgh6wO3Hwg6y2Q53nL00rv7aLRpFmh2kO7Ba0YZkbYmMBbH98IYoTU-Upan7KltzsTaVipsdimEid82yTHXNMgk2Ajob5Vt_yHtfX_DJtpoZ5TLq9TN2V4qj89WR8jadHaJVhFnuPMsGLRWMcLBY',
    reportedBy: {
      id: 'usr_john',
      name: 'John Doe',
      avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBALmeD0jHHqe-FvAIiC58dL06wTpxK6YRImjPnZRNj6IjKH-qBiQFPU7S0ceXP7m0AjjXdXrgikGKYwOdejbRzSpx05rOH2DKkkLgVAGbNbhRgwd_OOQveKikEIX21jAQp9v24GxI7-Xe-Irvk84T4O_1aSKG7fFeN35oQmsUEoNXLFhAqKKyrwlDWPOF7yj46gnBM4kGb6mTAGmgoo-3K0b9oJPzasjFRuVUoK-vpJ4d6US7X42c3Zc6i0g6XqCxtZwInOnhwKT0',
      email: 'j.doe@university.edu',
      role: 'student',
    },
    contactPreference: 'email',
    tags: ['Bose', 'Headphones', 'Cory Hall', 'Audio'],
    createdAt: '2025-05-07T20:10:00Z',
    updatedAt: '2025-05-07T20:10:00Z',
  },
  {
    id: 'itm_007',
    title: 'Brown Leather Bifold Wallet',
    category: 'Wallets & Bags',
    type: 'found',
    status: 'active',
    description: 'Found genuine brown leather wallet near South Hall shuttle stop. Contains student ID (initials M.R.) and bus pass. Kept safe at campus security.',
    primaryColor: 'Brown',
    brand: 'Fossil',
    location: {
      building: 'South Hall Bus Stop',
      roomOrArea: 'Bus Shelter Bench',
      campusZone: 'South Campus',
      lat: 37.8680,
      lng: -122.2590,
    },
    dateReported: '2025-05-06',
    timeReported: '09:00',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC1eclSm38CYbu98W95SE8jJaPQDUvmIOhasqQEvYBiZiLbuuJqztgUe0WGDMZXvEJwJhE80Ssh-sRj47KG3wmNoeTckYNQzERwODyjgCA4Pzds3NMD6w1_T6_f5Cx_WFPdn8nkTdkoiJaV3arEsou1kzu1aJDihxJKwdMjSs6SzWKYd_lAP6bfwP3P0r5m2ycpzwSvswlbvyvQW-vkMzK-uj44MPckjcWjqFp925UMtPeUCke-iA_AnkPR6Gme86a_XVPjwn8Jrng',
    reportedBy: {
      id: 'usr_admin',
      name: 'Dr. Robert Vance',
      avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDpexsvgPi6GB15nHlLoZCeZ0cYhHBLdfrYinpePSCjDqH-Na11weSEQ-U7N_YpeuAqRO84XmqEBWgfBT2KgEGP73NMr7p1mjBVXHDOBQmo5TlJlFYV_vzVH8KZtcL5k2YStUaF0s9xeb-hyKnLgbakeTzY09PT1hxpVFoUq7Y1leTklxQw8Fa5nxz4M8oBl1eBN6JL7T0DkkRPpyIgRd2_jl_zO-0OppsXjer3C-9Oi_71P_MvNL0TZ1sDp0dAHKs6yihQoAlSBt0',
      email: 'admin.lostfound@university.edu',
      role: 'admin',
    },
    contactPreference: 'in_app',
    storageLocation: 'Campus Security Safe Box #3',
    tags: ['Wallet', 'ID', 'South Hall', 'Leather'],
    createdAt: '2025-05-06T09:00:00Z',
    updatedAt: '2025-05-06T09:00:00Z',
  },
  {
    id: 'itm_008',
    title: 'Dark Blue Herschel Backpack',
    category: 'Wallets & Bags',
    type: 'found',
    status: 'active',
    description: 'Herschel Supply Co. navy backpack found outside Dwinelle Hall courtyard. Contains spiral notebooks, chemistry textbook, and a pink pencil pouch.',
    primaryColor: 'Dark Blue',
    brand: 'Herschel',
    location: {
      building: 'Dwinelle Hall',
      roomOrArea: 'Courtyard Benches',
      campusZone: 'Central Quad',
      lat: 37.8705,
      lng: -122.2600,
    },
    dateReported: '2025-05-05',
    timeReported: '15:15',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC_heKrnbxqoSZNYWFNICQ3XpJCoLolSmTV8Sxu6024aqlbaJD_Urx_sTyCc6XYfmlmwtST_Mvx1kMXXpSs376XesMlkVdFl6g96dTRDovr3ZUbYe_71X4n4mcvTewtYKGHNalVJn3KoPugku8pniu-GFTo6cPlUaGDS7xQfzPw7d0EjcrzP-jYbfStiHu77PmS14VJurvd3IiQgom6NdCjekOmgr6lKfsbqTuGhLXMMLLduu5I6tYa_Z0aBWjNpxc3grWYFjkekZs',
    reportedBy: {
      id: 'usr_sarah',
      name: 'Sarah Jenkins',
      avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDVBaqHvRkKTRymhte9qeP9sw12DxY4_azlQC9PWYfScmojcFoXe90MLA0zyOhkIJLEwdWF7rQISMC0U00Jtgmar6ndNxQPZA-EKXZE8rJ8WtnThF8tSZTIKaeuThUuygBOI2Aeg0dOCmP2wD9n0eioS93T_vpAlPqqBV98p59_MBFTreKu_ZzL3k5iZ3Gz-LegskFgR4AuzvWEGQigSC16fAWHvQlEh8eHFbpLwIZX8MIg_0liz33_OOq8YzEs729TEuAzRwgVTeM',
      email: 's.jenkins@university.edu',
      role: 'student',
    },
    contactPreference: 'in_app',
    storageLocation: 'Dwinelle Lost & Found Office 112',
    tags: ['Backpack', 'Herschel', 'Books', 'Dwinelle'],
    createdAt: '2025-05-05T15:15:00Z',
    updatedAt: '2025-05-05T15:15:00Z',
  },
  {
    id: 'itm_009',
    title: 'TI-84 Plus CE Graphing Calculator',
    category: 'Stationery & Study',
    type: 'lost',
    status: 'active',
    description: 'Black TI-84 Plus CE calculator lost in Math 54 discussion room (310 Evans Hall). Has small yellow tape on the back with "Math Dept" scribbled.',
    primaryColor: 'Black',
    brand: 'Texas Instruments',
    location: {
      building: 'Evans Hall',
      roomOrArea: 'Room 310',
      campusZone: 'North Campus',
      lat: 37.8735,
      lng: -122.2575,
    },
    dateReported: '2025-05-04',
    timeReported: '13:00',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCdU0KrH_HNhm1qIVhQOgPsjqaSAYZIa7Adztjn5lK4iDwbol9Qb1PJQlSfp7abAIUL5VUmwe02XVvUdiW8g5dtFeb-lTxDCdcEbteIXg1SNJC3EySs1_pWVQ1dvpPQkq3BtZb60_o_WhNCBXtwTsESPpR4o6TNeO4WCykRSl7tpZe5pSoLVD_3BGEVC5YQO1_qILiyrzXNuNwt2uXlR6iuKzqHjNLuVDnLzTyTBdm0rIye1vFUvyfQY0pJv2gvJhtaSVRwA9pod4g',
    reportedBy: {
      id: 'usr_john',
      name: 'John Doe',
      avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBALmeD0jHHqe-FvAIiC58dL06wTpxK6YRImjPnZRNj6IjKH-qBiQFPU7S0ceXP7m0AjjXdXrgikGKYwOdejbRzSpx05rOH2DKkkLgVAGbNbhRgwd_OOQveKikEIX21jAQp9v24GxI7-Xe-Irvk84T4O_1aSKG7fFeN35oQmsUEoNXLFhAqKKyrwlDWPOF7yj46gnBM4kGb6mTAGmgoo-3K0b9oJPzasjFRuVUoK-vpJ4d6US7X42c3Zc6i0g6XqCxtZwInOnhwKT0',
      email: 'j.doe@university.edu',
      role: 'student',
    },
    contactPreference: 'in_app',
    tags: ['Calculator', 'TI-84', 'Math', 'Evans'],
    createdAt: '2025-05-04T13:00:00Z',
    updatedAt: '2025-05-04T13:00:00Z',
  }
];

export const INITIAL_CLAIMS: ClaimRequest[] = [
  {
    id: 'clm_101',
    itemId: 'itm_005',
    itemTitle: 'AirPods Pro Gen 2 with Silicone Case',
    itemImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDG2CVIw4ECB-uni_gDHCF6a2FFqpd-euJhqm1vqeO4iYrnewwgnGS-n2kaND1UhFpUeG6lXVOZM_Eg8XJHy9EcgGdTm1pHa6IghX6fhVB-2otcZOzvUNkBT8ly42GlLXUQLPif5nuFhPal1PpwWZv9GoiUID9nhxTFsnLDNcFgEVC7ZbeVIwie83GU6CG5WCXeb_BGNNK5hidGD-m8qgWGGo3FFXlcaX_SFSnf6mLrR5wxX8Gclfmh41Z2s6AKrqaHmfCsSr-DO0o',
    claimerId: 'usr_john',
    claimerName: 'John Doe',
    claimerEmail: 'j.doe@university.edu',
    claimerAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBALmeD0jHHqe-FvAIiC58dL06wTpxK6YRImjPnZRNj6IjKH-qBiQFPU7S0ceXP7m0AjjXdXrgikGKYwOdejbRzSpx05rOH2DKkkLgVAGbNbhRgwd_OOQveKikEIX21jAQp9v24GxI7-Xe-Irvk84T4O_1aSKG7fFeN35oQmsUEoNXLFhAqKKyrwlDWPOF7yj46gnBM4kGb6mTAGmgoo-3K0b9oJPzasjFRuVUoK-vpJ4d6US7X42c3Zc6i0g6XqCxtZwInOnhwKT0',
    dateSubmitted: '2025-05-09',
    status: 'proof_requested',
    descriptionOfOwnership: 'I lost these near the Bear Cafe on Thursday morning! The Bluetooth name is "John\'s Pods" and inside the silicone case there is a slight scratch on the hinge.',
    adminNotes: 'Please upload a screenshot showing "John\'s Pods" connected in Find My or device settings.',
    pickupLocation: 'Student Union Information Desk #3',
    pickupCode: 'CLM-7842',
  }
];

export const INITIAL_ACTIVITY: ActivityLog[] = [
  {
    id: 'act_01',
    type: 'report_created',
    title: 'New Found Item Reported',
    description: 'Sarah Jenkins logged a Silver MacBook Pro 14" at Science Library.',
    timestamp: '10 mins ago',
    actorName: 'Sarah Jenkins',
    itemId: 'itm_001',
    badgeType: 'info'
  },
  {
    id: 'act_02',
    type: 'claim_submitted',
    title: 'Claim Submitted',
    description: 'John Doe submitted ownership verification for AirPods Pro Gen 2.',
    timestamp: '2 hours ago',
    actorName: 'John Doe',
    itemId: 'itm_005',
    badgeType: 'warning'
  },
  {
    id: 'act_03',
    type: 'item_resolved',
    title: 'Item Handed Over',
    description: 'Blue Backpack returned safely to owner Marcus Vance.',
    timestamp: 'Yesterday',
    actorName: 'Dr. Robert Vance',
    badgeType: 'success'
  }
];

export const CAMPUS_BUILDINGS = [
  'Science & Engineering Library',
  'MLK Jr. Student Union',
  'Evans Hall',
  'Cory Hall Engineering',
  'Dwinelle Hall',
  'Wheeler Hall Auditorium',
  'Recreation & Student Health Center',
  'South Hall',
  'Moffitt Library',
  'Haas School of Business',
  'Undergraduate Dormitory Complex A',
  'Faculty Club',
  'Botanical Garden Entrance',
];

export const ITEM_CATEGORIES = [
  'Electronics',
  'Keys & Cards',
  'Eyewear',
  'Bottles & Containers',
  'Audio',
  'Wallets & Bags',
  'Stationery & Study',
  'Apparel & Accessories',
  'Other'
];
